import re

from app.domain.catalogs import SOFTWARE_CATALOG
from app.domain.models import OperatingSystem, SoftwarePackage, VerifiedEmployeeProfile
from app.planner.service import generate_onboarding_plan
from app.setup_scripts.models import SetupScriptPreview


SOFTWARE_BY_ID: dict[str, SoftwarePackage] = {
    software.id: software for software in SOFTWARE_CATALOG
}

WINDOWS_WINGET_COMMAND_PATTERN = re.compile(
    r"^winget install --id ([A-Za-z0-9._-]+) --source winget$"
)

UNSAFE_COMMAND_MARKERS = (
    ";",
    "&&",
    "||",
    "|",
    ">",
    "<",
    "\n",
    "\r",
    "http://",
    "https://",
    "curl",
    "wget",
    "invoke-webrequest",
    "invoke-expression",
    "start-process",
    "cmd",
    "powershell",
    "password=",
    "token=",
    "api_key=",
)

COMPANY_VPN_SOFTWARE_ID = "company-vpn-client"
COMPANY_VPN_MANUAL_STEP = (
    "Company VPN Client requires operator approval before installation."
)


def generate_setup_script_preview(
    employee: VerifiedEmployeeProfile,
) -> SetupScriptPreview:
    if employee.operating_system is not OperatingSystem.windows:
        raise ValueError("MVP currently supports Windows PowerShell setup scripts only.")

    onboarding_result = generate_onboarding_plan(employee)
    software_ids = onboarding_result.plan.software_ids
    executable_commands: list[str] = []
    manual_steps: list[str] = []

    for software_id in software_ids:
        software = SOFTWARE_BY_ID.get(software_id)
        if software is None:
            raise ValueError(f"software ID is missing from catalog: {software_id}")
        if OperatingSystem.windows not in software.supported_operating_systems:
            raise ValueError(f"software does not support Windows: {software_id}")

        if software_id == COMPANY_VPN_SOFTWARE_ID:
            manual_steps.append(COMPANY_VPN_MANUAL_STEP)
            continue

        command = software.install_commands.get(OperatingSystem.windows)
        if command is None:
            raise ValueError(f"Windows install command is missing for software: {software_id}")

        executable_commands.append(normalize_windows_install_command(command))

    content = _build_powershell_content(
        executable_commands=executable_commands,
        manual_steps=manual_steps,
    )

    return SetupScriptPreview(
        employee_id=employee.employee_id,
        operating_system=employee.operating_system,
        filename=f"boardly-setup-{_sanitize_employee_id(employee.employee_id)}.ps1",
        software_ids=list(software_ids),
        executable_commands=executable_commands,
        manual_steps=manual_steps,
        content=content,
        requires_human_review=True,
        auto_execute=False,
    )


def normalize_windows_install_command(command: str) -> str:
    command_lower = command.lower()
    if any(marker in command_lower for marker in UNSAFE_COMMAND_MARKERS):
        raise ValueError("unsafe Windows install command")

    match = WINDOWS_WINGET_COMMAND_PATTERN.fullmatch(command)
    if match is None:
        raise ValueError("Windows install command must match the winget allowlist")

    package_id = match.group(1)
    return (
        f"winget install --id {package_id} --source winget --silent "
        "--accept-package-agreements --accept-source-agreements"
    )


def _sanitize_employee_id(employee_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9-]", "-", employee_id)


def _build_powershell_content(
    executable_commands: list[str],
    manual_steps: list[str],
) -> str:
    lines = [
        "# Generated by Boardly",
        "# Human review is required before execution.",
        "# Boardly does not execute this script.",
        "",
        '$ErrorActionPreference = "Stop"',
        "",
    ]
    lines.extend(executable_commands)

    if manual_steps:
        lines.extend(["", "# Manual steps"])
        lines.extend(f"# {step}" for step in manual_steps)

    return "\n".join(lines)
